# Generated by Django 3.2.7 on 2021-09-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='length',
            new_name='distance',
        ),
    ]
