name: Django CI

on:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Pipenv
        run: pip install pipenv
          
      - name: Install Dependencies
        working-directory: ./app
        run: pipenv install --dev
        
      - name: Run tests
        working-directory: ./app
        run: pipenv run python manage.py test
